apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "ingresses"]  # Example resources, adjust as needed
  verbs: ["create", "get", "update", "delete", "list", "watch"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: default  # Adjust the namespace as per your requirements
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  annotations:
    kubernetes.io/service-account.name: deployer  # Associate with the deployer ServiceAccount
type: kubernetes.io/service-account-token