apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: alikhames/new-java-app:7
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: java-app
    
