- name: Create namespace for Grafana
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring

- name: Install Grafana
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/grafana/grafana/main/deploy/kubernetes/grafana.yaml') }}"
