- name: Create namespace for Prometheus
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring

- name: Install Prometheus Operator
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml') }}"

- name: Create Prometheus instance
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    definition: |
      apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: k8s
      spec:
        serviceMonitorSelector: {}
        resources:
          requests:
            memory: 400Mi
